clean: true
objc: false
readme: Readme.md
framework_root: MBAudienceSwift
module: MBAudienceSwift
module_version: 0.1
sdk: iphonesimulator

xcodebuild_arguments:
    - "-workspace"
    - "MBAudienceSwift.xcworkspace"
    - "-scheme"
    - "MBAudienceSwift"

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://github.com/Mumble-SRL/MBAudienceSwift

theme: fullwidth

custom_categories:
  - name: MBAudience
    children:
    - MBAudience
    - MBAudienceDelegate
